export type ChainMetricRawNode = {
  display_name: string;
  node_id: string;
  service_name: string;
  api_name: string;
  cost_in_us: number;
  trace_count: number;
  trace_count_percentage: number;
  span_count: number;
  span_count_percentage: number;
  error_trace_count: number;
  error_trace_count_percentage: number;
  local_pure_cost_in_us: number;
  network_cost_in_us: number;
  max_children_count: string;
  children: ChainMetricRawNode[];
};

export const chainMetricDemoData: ChainMetricRawNode = {
  display_name: "server_b::/resource_bb",
  node_id: "[server]server_b&/resource_bb&request",
  service_name: "server_b",
  api_name: "/resource_bb",
  cost_in_us: 1315497.729,
  trace_count: 188,
  trace_count_percentage: 1,
  span_count: 243,
  span_count_percentage: 1.2925531914893618,
  error_trace_count: 0,
  error_trace_count_percentage: 0,
  local_pure_cost_in_us: 39424.234,
  network_cost_in_us: 0,
  max_children_count: "20",
  children: [
    {
      display_name: "server_c::http_call",
      node_id: "[client]server_b&/resource_bb&http_call",
      service_name: "server_c",
      api_name: "http_call",
      cost_in_us: 970485,
      trace_count: 1,
      trace_count_percentage: 0.005319148936170213,
      span_count: 1,
      span_count_percentage: 1,
      error_trace_count: 0,
      error_trace_count_percentage: 0,
      local_pure_cost_in_us: 0,
      network_cost_in_us: 0,
      max_children_count: "0",
      children: [],
    },
    {
      display_name: "server_c::/resource_cc",
      node_id:
        "[client]server_b&/resource_bb&http_call|[server]server_c&/resource_cc&request",
      service_name: "server_c",
      api_name: "/resource_cc",
      cost_in_us: 845146.234,
      trace_count: 188,
      trace_count_percentage: 1,
      span_count: 242,
      span_count_percentage: 1.2872340425531914,
      error_trace_count: 0,
      error_trace_count_percentage: 0,
      local_pure_cost_in_us: 65.989,
      network_cost_in_us: 651.617,
      max_children_count: "2",
      children: [
        {
          display_name: "server_c::/resource_cc",
          node_id: "[common]server_c&/resource_cc&sleep",
          service_name: "server_c",
          api_name: "/resource_cc",
          cost_in_us: 833561.112,
          trace_count: 188,
          trace_count_percentage: 1,
          span_count: 242,
          span_count_percentage: 1.2872340425531914,
          error_trace_count: 0,
          error_trace_count_percentage: 0,
          local_pure_cost_in_us: 833561.112,
          network_cost_in_us: 0,
          max_children_count: "0",
          children: [],
        },
        {
          display_name: "mysql:localhost/byteapm::mysql.query",
          node_id: "[client]server_c&/resource_cc&mysql.query",
          service_name: "mysql:localhost/byteapm",
          api_name: "mysql.query",
          cost_in_us: 2674.191,
          trace_count: 188,
          trace_count_percentage: 1,
          span_count: 484,
          span_count_percentage: 2.574468085106383,
          error_trace_count: 0,
          error_trace_count_percentage: 0,
          local_pure_cost_in_us: 0,
          network_cost_in_us: 0,
          max_children_count: "0",
          children: [],
        },
      ],
    },
    {
      display_name: "server_d::/resource_dd",
      node_id:
        "[client]server_b&/resource_bb&http_call|[server]server_d&/resource_dd&request",
      service_name: "server_d",
      api_name: "/resource_dd",
      cost_in_us: 713728.957,
      trace_count: 69,
      trace_count_percentage: 0.3670212765957447,
      span_count: 81,
      span_count_percentage: 1.173913043478261,
      error_trace_count: 0,
      error_trace_count_percentage: 0,
      local_pure_cost_in_us: 73.014,
      network_cost_in_us: 637.594,
      max_children_count: "5",
      children: [
        {
          display_name: "server_d::/resource_dd",
          node_id: "[common]server_d&/resource_dd&sleep",
          service_name: "server_d",
          api_name: "/resource_dd",
          cost_in_us: 693547.42,
          trace_count: 69,
          trace_count_percentage: 0.3670212765957447,
          span_count: 81,
          span_count_percentage: 1.173913043478261,
          error_trace_count: 0,
          error_trace_count_percentage: 0,
          local_pure_cost_in_us: 693547.42,
          network_cost_in_us: 0,
          max_children_count: "0",
          children: [],
        },
        {
          display_name: "mysql:127.0.0.1/byteapm::mysql.query",
          node_id: "[client]server_d&/resource_dd&mysql.query",
          service_name: "mysql:127.0.0.1/byteapm",
          api_name: "mysql.query",
          cost_in_us: 457.014,
          trace_count: 69,
          trace_count_percentage: 0.3670212765957447,
          span_count: 161,
          span_count_percentage: 2.3333333333333335,
          error_trace_count: 0,
          error_trace_count_percentage: 0,
          local_pure_cost_in_us: 0,
          network_cost_in_us: 0,
          max_children_count: "0",
          children: [],
        },
        {
          display_name: "redis:localhost::redis.command",
          node_id: "[client]server_d&/resource_dd&redis.command",
          service_name: "redis:localhost",
          api_name: "redis.command",
          cost_in_us: 317.826,
          trace_count: 69,
          trace_count_percentage: 0.3670212765957447,
          span_count: 162,
          span_count_percentage: 2.347826086956522,
          error_trace_count: 0,
          error_trace_count_percentage: 0,
          local_pure_cost_in_us: 0,
          network_cost_in_us: 0,
          max_children_count: "0",
          children: [],
        },
        {
          display_name: "kafka:127.0.0.1 topic:test_topic::kafka.produce",
          node_id: "[client]server_d&/resource_dd&kafka.produce",
          service_name: "kafka:127.0.0.1 topic:test_topic",
          api_name: "kafka.produce",
          cost_in_us: 137.145,
          trace_count: 69,
          trace_count_percentage: 0.3670212765957447,
          span_count: 81,
          span_count_percentage: 1.173913043478261,
          error_trace_count: 0,
          error_trace_count_percentage: 0,
          local_pure_cost_in_us: 0,
          network_cost_in_us: 0,
          max_children_count: "0",
          children: [],
        },
      ],
    },
    {
      display_name: "server_d::unknown",
      node_id:
        "[client]server_b&/resource_bb&http_call|[server]server_d&unknown&request",
      service_name: "server_d",
      api_name: "unknown",
      cost_in_us: 876.592,
      trace_count: 49,
      trace_count_percentage: 0.26063829787234044,
      span_count: 67,
      span_count_percentage: 1.3673469387755102,
      error_trace_count: 0,
      error_trace_count_percentage: 0,
      local_pure_cost_in_us: 21.633,
      network_cost_in_us: 854.959,
      max_children_count: "0",
      children: [],
    },
    {
      display_name: "java_server_a::/java_service_a/http",
      node_id:
        "[client]server_b&/resource_bb&http_call|[server]java_server_a&/java_service_a/http&http.called",
      service_name: "java_server_a",
      api_name: "/java_service_a/http",
      cost_in_us: 206502.2,
      trace_count: 60,
      trace_count_percentage: 0.3191489361702128,
      span_count: 78,
      span_count_percentage: 1.3,
      error_trace_count: 0,
      error_trace_count_percentage: 0,
      local_pure_cost_in_us: 622.15,
      network_cost_in_us: 573.35,
      max_children_count: "7",
      children: [
        {
          display_name: "java_server_a::/java_service_a/http",
          node_id: "[common]java_server_a&/java_service_a/http&spring.controller",
          service_name: "java_server_a",
          api_name: "/java_service_a/http",
          cost_in_us: 205339.633,
          trace_count: 60,
          trace_count_percentage: 0.3191489361702128,
          span_count: 78,
          span_count_percentage: 1.3,
          error_trace_count: 0,
          error_trace_count_percentage: 0,
          local_pure_cost_in_us: 69223.717,
          network_cost_in_us: 0,
          max_children_count: "6",
          children: [
            {
              display_name: "java_server_a::/java_service_a/http",
              node_id: "[common]java_server_a&/java_service_a/http&spring.annotation",
              service_name: "java_server_a",
              api_name: "/java_service_a/http",
              cost_in_us: 136115.917,
              trace_count: 60,
              trace_count_percentage: 0.3191489361702128,
              span_count: 78,
              span_count_percentage: 1.3,
              error_trace_count: 0,
              error_trace_count_percentage: 0,
              local_pure_cost_in_us: 57.633,
              network_cost_in_us: 0,
              max_children_count: "6",
              children: [
                {
                  display_name: "java_server_b::/java_service_b/http",
                  node_id:
                    "[client]java_server_a&/java_service_a/http&http.call|[server]java_server_b&/java_service_b/http&http.called",
                  service_name: "java_server_b",
                  api_name: "/java_service_b/http",
                  cost_in_us: 136292.883,
                  trace_count: 60,
                  trace_count_percentage: 0.3191489361702128,
                  span_count: 78,
                  span_count_percentage: 1.3,
                  error_trace_count: 0,
                  error_trace_count_percentage: 0,
                  local_pure_cost_in_us: 438,
                  network_cost_in_us: 632.917,
                  max_children_count: "5",
                  children: [
                    {
                      display_name: "java_server_b::/java_service_b/http",
                      node_id:
                        "[common]java_server_b&/java_service_b/http&spring.controller",
                      service_name: "java_server_b",
                      api_name: "/java_service_b/http",
                      cost_in_us: 134987.367,
                      trace_count: 60,
                      trace_count_percentage: 0.3191489361702128,
                      span_count: 78,
                      span_count_percentage: 1.3,
                      error_trace_count: 0,
                      error_trace_count_percentage: 0,
                      local_pure_cost_in_us: 927.85,
                      network_cost_in_us: 0,
                      max_children_count: "4",
                      children: [
                        {
                          display_name: "java_server_b::/java_service_b/http",
                          node_id:
                            "[common]java_server_b&/java_service_b/http&spring.annotation",
                          service_name: "java_server_b",
                          api_name: "/java_service_b/http",
                          cost_in_us: 63977.333,
                          trace_count: 60,
                          trace_count_percentage: 0.3191489361702128,
                          span_count: 156,
                          span_count_percentage: 2.6,
                          error_trace_count: 0,
                          error_trace_count_percentage: 0,
                          local_pure_cost_in_us: 0,
                          network_cost_in_us: 0,
                          max_children_count: "2",
                          children: [


                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
